name: Publish to crates.io when v* tags

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    environment: publish
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Publish to crates.io
        run: cargo publish --verbose
