name: Cargo dependencies audit

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: '*'
    paths:
    - '**/Cargo.toml'
    - '**/Cargo.lock'
  pull_request:
    branches: [ main, master, dev, develop ]
    paths:
    - '**/Cargo.toml'
    - '**/Cargo.lock'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
