name: Check & Test

on:
  push:
    branches: [ '*', '!**-nightly' ]
    paths:
    - '.github/workflows/rust-check-test.yml'
    - '**/*.rs'
    - '**/*.md' # Test examples in markdowns included as API doc
    - '**/Cargo.toml'
    - '**/Cargo.lock'
  pull_request:
    branches: [ '*', '!**-nightly' ]
    paths:
    - '.github/workflows/rust-check-test.yml'
    - '**/*.rs'
    - '**/*.md' # Test examples in markdowns included as API doc
    - '**/Cargo.toml'
    - '**/Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        rust: [ stable, beta ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Check
      run: cargo check --verbose
    - name: Tests
      run: cargo test --verbose -- --show-output
    - name: Ignored tests
      run: cargo test --verbose -- --show-output --ignored
    - name: Dry run publish
      run: cargo publish --dry-run --verbose
